language: android
sudo: false
notifications:
  email: false

android:
  components:
    - build-tools-28.0.2,android-28,extra-android-m2repository,platform-tools
addons:
  apt:
    packages:
      - autoconf
      - pkg-config
      - libtool

before_install:
  - sdkmanager "platforms;android-28"
  - buildscripts/.travis.sh install
script:
  - buildscripts/.travis.sh build
